SET maintenance_work_mem = '8GB';

CREATE INDEX CONCURRENTLY jhw_activity_counts_on_company_id ON activity_counts (company_id);
CREATE INDEX CONCURRENTLY jhw_activity_logs_on_company_id ON activity_logs (company_id);
CREATE INDEX CONCURRENTLY jhw_addresses_on_company_id ON addresses (company_id);
CREATE INDEX CONCURRENTLY jhw_api_keys_on_company_id ON api_keys (company_id);
CREATE INDEX CONCURRENTLY jhw_company_users_on_company_id ON company_users (company_id);
CREATE INDEX CONCURRENTLY jhw_contact_suggestions_on_company_id ON contact_suggestions (company_id);
CREATE INDEX CONCURRENTLY jhw_correspondences_on_company_id ON correspondences (company_id);
CREATE INDEX CONCURRENTLY jhw_custom_fields_on_company_id ON custom_fields (company_id);
CREATE INDEX CONCURRENTLY jhw_entity_associations_on_company_id ON entity_associations (company_id);
CREATE INDEX CONCURRENTLY jhw_field_layout_items_on_company_id ON field_layout_items (company_id);
CREATE INDEX CONCURRENTLY jhw_field_layouts_on_company_id ON field_layouts (company_id);
CREATE INDEX CONCURRENTLY jhw_file_documents_on_company_id ON file_documents (company_id);
CREATE INDEX CONCURRENTLY jhw_gmail_msgid_mappings_on_company_id ON gmail_msgid_mappings (company_id);
CREATE INDEX CONCURRENTLY jhw_goal_memberships_on_company_id ON goal_memberships (company_id);
CREATE INDEX CONCURRENTLY jhw_group_permissions_on_company_id ON group_permissions (company_id);
CREATE INDEX CONCURRENTLY jhw_import_statuses_on_company_id ON import_statuses (company_id);
CREATE INDEX CONCURRENTLY jhw_organization_suggestions_on_company_id ON organization_suggestions (company_id);
CREATE INDEX CONCURRENTLY jhw_organizations_on_company_id ON organizations (company_id);
CREATE INDEX CONCURRENTLY jhw_serialized_entities_on_company_id ON serialized_entities (company_id);
CREATE INDEX CONCURRENTLY jhw_stage_entry_logs_on_company_id ON stage_entry_logs (company_id);
CREATE INDEX CONCURRENTLY jhw_typed_properties_on_company_id ON typed_properties (company_id);
CREATE INDEX CONCURRENTLY jhw_user_feedback_responses_on_company_id ON user_feedback_responses (company_id);
CREATE INDEX CONCURRENTLY jhw_zero_input_ingestions_on_company_id ON zero_input_ingestions (company_id);
