[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[term]
quiet      = false    # whether cargo output is quiet
verbose    = false    # whether cargo provides verbose output
color      = 'always' # whether cargo colorizes output
hyperlinks = true     # whether cargo inserts links into output

[alias]
r  = "run jhw"
rr = "run --release jhw"
